config/routes.rb
Rails.application.routes.draw do
  
  resources :todo_lists
  resources :to_lists
  resources :recipes
  resources :projects




  devise_scope :user do
	  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
	  get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
	  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
	  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  root                    to: 'itineraries#index'
  #get '*path',          to: 'home#index', via: :all
  resources :jobs, :products, :categories, :customers
  resources :dashboards
  
  resources :recommendations do
	  member do
		  get 'approve'
		  get 'reject'
	  end
	  collection do
		  get 'for_approval'
		  get 'approved'
		  get 'rejected'
		  
	  end
  end
  
  
  resources :expenses do
	  member do
		  get 'approve'
		  get 'reject'
	  end
	  collection do
		  get 'search_tcn_no'
		  get 'for_approval'
		  get 'approved'
		  get 'rejected'
		 
	  end
  end
  
  resources :activities do
	  member do
		  get 'approve'
		  get 'reject'
	  end
       collection do
            get 'search_control_no'
		  get 'for_approval'
		  get 'approved'
		  get 'rejected'
		
       end
  end
  resources :itineraries do
	  member do
            get 'completed'
		  get 'update_status_visit_list'
		  get 'approve'
		  get 'reject'
	  end
	  collection do
		  get 'current_week'
		  get 'approved'
		  get 'rejected'
		
	  end
	  
  end
  resources :users do
	  collection do
		  get 'show_current_user'
	  end
  end
  
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
	belongs_to :user
	has_many :visit_lists, dependent: :destroy
	accepts_nested_attributes_for :visit_lists, allow_destroy: true, reject_if: :all_blank
	validates :iti_period_from, presence: true
	validates :iti_period_to, presence: true
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
     protect_from_forgery with: Exception
	before_action :no_owner, only: [:edit]
	
	def index
     	if current_user.admin? or current_user.admin2?
			@itineraries = Itinerary.paginate(page: params[:page]).order(created_at: :desc)
			@status = Itinerary.where("iti_period_from >= ? and iti_period_to <= ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).all
			@itineraries_admin = current_user.itineraries.paginate(page: params[:page]).order(created_at: :desc)
			@status_admin = current_user.itineraries.where("iti_period_from >= ? and iti_period_to <= ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).all
		else
			@itineraries = current_user.itineraries.paginate(page: params[:page]).order(created_at: :desc)
			@status = current_user.itineraries.where("iti_period_from >= ? and iti_period_to <= ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).all
		end
	
     end
     
	def show
          @itinerary = Itinerary.find(params[:id])
     end

     def new
		@itinerary_last = current_user.itineraries.last
	     @itinerary = current_user.itineraries.new
	end

     def create
		@itinerary = current_user.itineraries.build(itinerary_params)
          if @itinerary.save
			@itinerary.update_columns(iti_created: true)
               flash[:success] = "Itenerary created..."
               redirect_to @itinerary
          else
               render 'new'
          end
     end

     def edit
          @itinerary = if current_user.admin? || current_user.admin2?
					   Itinerary.find(params[:id])
				   else
					   current_user.itineraries.find(params[:id])
				   end
	end

     def update
          @itinerary = if current_user.admin? || current_user.admin2?
					   Itinerary.find(params[:id])
				   else
					   current_user.itineraries.find(params[:id])
				   end
			 
          if @itinerary.update(itinerary_params)
			@itinerary.update(iti_rejected: false)
		     flash[:success] = "Itinerary modified"
               redirect_to @itinerary
          else
               render "edit"
          end

     end

     def destroy
		@itinerary = if current_user.admin? || current_user.admin2?
					   Itinerary.find(params[:id])
				   else
					   current_user.itineraries.find(params[:id]).destroy
				   end
		  
          if @itinerary.destroy
               flash[:danger] = "Itinerary deleted"
               redirect_to itineraries_url
          else
               flash[:warning] = "Error in delete"
               redirect_to itineraries_url
          end
     end
  	
	def update_status_visit_list
		@visit = VisitList.find(params[:id])
		if @visit.update(visit_completed: true)
			redirect_to itinerary_url @visit.itinerary
			flash[:success] = "Status updated..."
		end
	end
	
	def current_week
		check_admin_admin2
		@itineraries = Itinerary.where("(iti_period_from >= ? and iti_period_to <= ?) and iti_status = ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week, false).paginate(page: params[:page]).order(created_at: :desc)
		@status = Itinerary.where("iti_period_from >= ? and iti_period_to <= ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).all
		@itineraries_admin = current_user.itineraries.paginate(page: params[:page]).order(created_at: :desc)
		@status_admin = current_user.itineraries.where("iti_period_from >= ? and iti_period_to <= ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).all
	end
	
	def approved
		check_admin_admin2
		@itineraries = Itinerary.where("(iti_period_from >= ? and iti_period_to <= ?) and iti_status = ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week, true).paginate(page: params[:page]).order(created_at: :desc)
		@status = Itinerary.where("iti_period_from >= ? and iti_period_to <= ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).all
		@itineraries_admin = current_user.itineraries.paginate(page: params[:page]).order(created_at: :desc)
		@status_admin = current_user.itineraries.where("iti_period_from >= ? and iti_period_to <= ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).all
	
	end
	
	def rejected
		check_admin_admin2
		@itineraries = Itinerary.where("(iti_period_from >= ? and iti_period_to <= ?) and iti_rejected = ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week, true).paginate(page: params[:page]).order(created_at: :desc)
		@status = Itinerary.where("iti_period_from >= ? and iti_period_to <= ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).all
		@itineraries_admin = current_user.itineraries.paginate(page: params[:page]).order(created_at: :desc)
		@status_admin = current_user.itineraries.where("iti_period_from >= ? and iti_period_to <= ?", Time.zone.now.beginning_of_week, Time.zone.now.end_of_week).all
	end
	
	def approve
		check_admin_admin2
		@itinerary = Itinerary.find(params[:id])
		if @itinerary.update(iti_status: true, iti_rejected: false)
			flash[:success] = "Itinerary approved successfully..."
			redirect_to current_week_itineraries_url
		else
			flash[:danger] = "Error in approving itinerary..."
			redirect_to current_week_itineraries_url
		end
	end
	
	def reject
		check_admin_admin2
		@itinerary = Itinerary.find(params[:id])
		if @itinerary.update(iti_rejected: true)
			flash[:success] = "Itinerary rejected successfully"
			redirect_to current_week_itineraries_url
		else
			flash[:danger]  = "Error in rejecting itinerary"
			redirect_to current_week_itineraries_url
		end
	end
		
     private
     def itinerary_params
		params.require(:itinerary).permit(:iti_period_from, :iti_period_to,
								    visit_lists_attributes: VisitList.attribute_names.map(&:to_sym).push(:_destroy))
	end
	
	def no_owner
		unless  current_user.admin? or current_user.admin2
			@itinerary = current_user.itineraries.find_by(id: params[:id])
			if @itinerary.nil?
				flash[:warning] = "You don't have a  previlige"
				redirect_to itineraries_url
			end
		
		end
		
	end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/itineraries/_visit_list_fields.html.erb
<div class="nested-fields">
     <div class="row form-group">
          <div class="col-lg-1 mb-3">
               <%= f.hidden_field :_destroy %>
               <%= link_to "Remove", "#", class: "btn btn-danger btn-sm", data: {action: "click->nested-form#remove_association"} %>
          </div>
          <div class="col-lg-2 mb-3">
               <%= f.text_field :visit_date,
                                data: {
                                     controller: "flatpickr",
                                     flatpickr_date_format: "%A, %B %d, %Y",
                                     flatpickr_min_date: Time.zone.now.beginning_of_week(:monday)
                                } , class: "form-control form-control-user", placeholder: "Choose a date", style: "background:#fff;"%>
          </div>
          <div class="col-lg-3 mb-3">
               <%= f.text_field :visit_place, class: "form-control form-control-user", placeholder: "Input Place..." %>
          </div>
          <div class="col-lg-3 mb-3">
               <%= f.text_field :visit_account, list: "list-account", class: "form-control form-control-user", placeholder: "Input account..." %>
               <datalist id="list-account">
                    <% Customer.all.each do |customer| %>
                         <option value="<%= customer.company %>"></option>
                    <% end %>
               </datalist>
          </div>
          <div class="col-lg-3 mb-3">
               <%= f.text_field :visit_person, class: "form-control form-control-user", placeholder: "Input contact person..." %>
          </div>
     </div>
</div>

app/views/itineraries/approved.html.erb
<div class="container-fluid">
     <!-- Page Heading -->
     <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Welcome Back, <%= current_user.firstname %> !</h1>
          <%  time = Time.new %>
          <h1 class="h3 mb-0 text-gray-800">Today is <%=  time.strftime("%A %B %d, %Y") %> </h1>
     </div>
     <!--  Itinerary status and summary-->
     <div class="row">
          <div class="col-xl-6 col-md-6 mb-4">
               <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                         <div class="row no-gutters align-items-center">
                              <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Number of Itineraries</div>
                                   <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        <% count = current_user.admin? ? @itineraries_admin.count : @itineraries.count %>
                                        <% if count.equal? 0 %>
                                             <p>You don't have any itinerary created</p>
                                        <% else %>
                                             <p>You have created <%= pluralize(count, "itinerary")%></p>
                                        <% end %>
                                        <%= link_to new_itinerary_path, class: "btn btn-primary btn-icon-split"  do %>
									<span class="icon text-white-50">
									<i class="fas fa-plus"></i>
									</span>
                                             <span class="text">Create Itinerary</span>
                                        <% end %>
                                   </div>
                              </div>
                              <div class="col-auto">
                                   <i class="fas fa-calendar fa-2x text-gray-300"></i>
                              </div>
                         </div>
                    </div>
               </div>
          </div>

          <div class="col-xl-6 col-md-6 mb-4">
               <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body">
                         <div class="row no-gutters align-items-center">
                              <div class="col mr-2">
                                   <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Status of Itinerary</div>
                                   <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        <% if current_user.admin? ? @status_admin.empty? : @status.empty? %>
                                             <p>You don't have any itinerary created</p>
                                        <% else %>
                                             <p>You have <%= pluralize(current_user.admin? ? @status_admin.where(iti_status: true).count : @status.where(iti_status: true).count, "weekly itinerary") %> approved</p>
                                             <p>You have <%= pluralize(current_user.admin? ? @status_admin.where(iti_status: false).count : @status.where(iti_status: false).count, "weekly itinerary") %> waiting for approval</p>
                                        <% end %>
                                   </div>
                              </div>
                              <div class="col-auto">
                                   <i class="fas fa-question fa-2x text-gray-300"></i>
                              </div>
                         </div>
                    </div>
               </div>
          </div>


     </div>
     <!-- End of Itinerary status and summary-->

     <!--     Display itinerary-->
     <div class="row justify-content-md-center" >
          <div class="col-lg-12">
               <div class="card shadow mb-4">
                    <div class="card-header py-3">
                         <h6 class="m-0 font-weight-bold text-primary">List of Itineraraies</h6>
                    </div>
                    <% if @itineraries.empty?  %>
                         <div class="card-body">
                              <div class="alert alert-info py-5">
                                   <h1 class="h1 mb-0 text-gray-800 text-center">List of approved itineraries is empty</h1>
                              </div>
                         </div>
                    <% end %>
                    <div class="card-body custom-hover">
                         <% @itineraries.each do |itinerary| %>
                              <%= link_to itinerary do %>
                                   <div class="row">
                                        <div class="col-xl-12 col-md-12 mb-4">
                                             <div class="card border-left-primary shadow h-100 py-2 itinerary-hover">
                                                  <div class="card-body">
                                                       <div class="row no-gutters align-items-center">
                                                            <div class="col-lg-6">
                                                                 <div class="font-weight-bold text-primary mb-2"><%=  "date period: ".titleize + itinerary.iti_period_from.strftime("%A %B %-d, %Y").concat(" to ").concat(itinerary.iti_period_to.strftime("%A %B %-d, %Y")) %></div>                                                                 <div class="h5 mb-1 font-weight-bold text-gray-800">
                                                            </div>
                                                                 <div class="h4 mb-1 text-gray-800">
                                                                      Number of People To Visit: <%= itinerary.visit_lists.count %>
                                                                 </div>
                                                                 <% unless current_user.admin? || current_user.admin2? %>
                                                                      <em>You cannot create another itinerary for this week, edit/modify your weekly itinerary instead.</em>
                                                                 <% end %>
                                                                 <% if current_user.admin? || current_user.admin2?%>
                                                                      <h1 class="h5 mb-0 text-gray-800"><em><%= itinerary.user.lastname.concat(", ").concat(itinerary.user.firstname) %></em></h1>
                                                                 <% end %>
                                                            </div>
                                                            <div class="col-lg-6">
                                                                 <span>
                                                                      <%= cl_image_tag("approved_wruqds", class: "float-right",  :width=>200, :crop=>"scale") %>

                                                                 </span>

                                                            </div>

                                                       </div>
                                                  </div>
                                             </div>
                                        </div>

                                   </div>
                              <% end  %>
                         <% end %>
                    </div>
               </div>
          </div>
     </div>
     <!--     End of display itinerary-->


</div>

app/views/itineraries/show.html.erb
<div class="container-fluid">
     <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800">Week Itinerary
          </h1>
     </div>
     <% admin = current_user.admin? || current_user.admin2? %>
     <% owner = current_user.itineraries.find_by(id: @itinerary.id).present? %>
     <form class="user">
          <div class="row">
               <div class="col-lg-12">
                    <div class="card shadow mb-4">
                         <div class="card-header py-3">
                              <h6 class="m-0 font-weight-bold text-primary">Itinerary Details<% %></h6>
                         </div>
                         <div class="card-body">
                              <div class="card-body">
                                   <div class="row form-group mb-5">
                                        <div class="col-lg-4 mb-3">
                                             <input type="text" value="<%= @itinerary.user.firstname.concat(" ").concat(@itinerary.user.lastname) %>" class="form-control form-control-user" style="background: #fff;" disabled>
                                        </div>
                                        <div class="col-lg-4 mb-3">
                                             <input type="text" value="<%= @itinerary.iti_period_from.strftime("%A %B %-d, %Y") %>" class="form-control form-control-user" style="background: #fff;" disabled>
                                        </div>
                                        <div class="col-lg-4 mb-3">
                                             <input type="text" value="<%= @itinerary.iti_period_to.strftime("%A %B %-d, %Y") %>" class="form-control form-control-user" style="background: #fff;" disabled>
                                        </div>
                                   </div>
                                   <div class="row table-responsive mb-3">
                                        <div class="col-lg-12">
                                             <table class="table table-striped">
                                                  <thead>
                                                  <tr>
                                                       <th scope="col">Action</th>
                                                       <th scope="col">Date</th>
                                                       <th scope="col">Place</th>
                                                       <th scope="col">Account</th>
                                                       <th scope="col">Person To Visit</th>
                                                       <th scope="col">Status</th>
                                                  </tr>
                                                  </thead>
                                                  <tbody>

                                                  <% @itinerary.visit_lists.all.order(:visit_date).each do |itinerary| %>
                                                       <tr>
                                                            <td>
                                                                 <% if admin or owner %>
                                                                      <% if @itinerary.iti_status? %>
                                                                           <% disabled_button = itinerary.visit_completed? ? "disabled" : "" %>
                                                                           <%= link_to "Update To Visited", update_status_visit_list_itinerary_url(itinerary), class: "btn btn-primary #{disabled_button}" %>
                                                                      <% else %>
                                                                           <p>For approval</p>
                                                                      <% end %>
                                                                 <% else %>
                                                                      <p>This section is reserved of the owner fo the itinerary</p>
                                                                 <% end %>
                                                            </td>
                                                            <td><%= itinerary.visit_date.strftime("%A %B %-d, %Y") %></td>
                                                            <td><%= itinerary.visit_place %></td>
                                                            <td><%= itinerary.visit_account %></td>
                                                            <td><%= itinerary.visit_person %></td>
                                                            <td>

                                                                      <% if itinerary.visit_completed? %>
                                                                           Visited
                                                                      <% else %>
                                                                           To be visited
                                                                      <% end %>

                                                            </td>

                                                       </tr>
                                                  <% end %>
                                                  </tbody>
                                             </table>
                                        </div>
                                   </div>

                                   <div class="row">
                                        <div class="col-lg-12">
                                             <h1 class="h5 mb-0 text-gray-800 mb-2">
                                                  Prepared by: <%= @itinerary.user.firstname + " " + @itinerary.user.lastname %>
                                             </h1>
                                             <h1 class="h6 mb-0 text-gray-800">
                                                  Prepared by: <%= @itinerary.user.job.title %>
                                             </h1>
                                        </div>
                                   </div>
                              </div>
                         </div>
                    </div>
               </div>
          </div>
     </form>

     <!--start buttons-->
     <% if admin %>
          <% disabled_button = @itinerary.iti_status? ? "disabled" : "" %>
          <div class="row">
               <div class="col-lg-6 mb-3">
                    <%= link_to approve_itinerary_url, class: "btn btn-primary btn-icon-split btn-block btn-lg #{disabled_button}"  do %>
                                             <span class="icon text-white-50">
                                             <i class="fas fa-thumbs-up"></i>
                                             </span>
                         <span class="text">Approve</span>
                    <% end %>

               </div>
               <div class="col-lg-6 mb-3">
                    <%= link_to reject_itinerary_url, class: "btn btn-secondary btn-icon-split btn-block btn-lg #{disabled_button}"  do %>
                                             <span class="icon text-white-50">
                                             <i class="fas fa-thumbs-down"></i>
                                             </span>
                         <span class="text">Reject</span>
                    <% end %>
               </div>
          </div>
     <% end %>
     <% if admin or owner %>
          <% disabled_button = @itinerary.iti_status? ? "disabled" : "" %>
          <div class="row">
               <div class="col-lg-6 mb-3">
                    <%= link_to edit_itinerary_url, class: "btn btn-info btn-icon-split btn-block btn-lg #{disabled_button}"  do %>
                                             <span class="icon text-white-50">
                                             <i class="fas fa-edit"></i>
                                             </span>
                         <span class="text">Modify</span>
                    <% end %>
               </div>
               <div class="col-lg-6">
                    <%= link_to @itinerary, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-icon-split btn-block btn-lg #{disabled_button}" do %>
                                             <span class="icon text-white-50">
                                                  <i class="fas fa-trash"></i>
                                             </span>
                         <span class="text">Delete</span>
                    <% end %>
               </div>


          </div>
     <% end %>
     <!--end buttons-->
</div>