config/routes.rb
Rails.application.routes.draw do
  
  resources :todo_lists
  resources :to_lists
  resources :recipes
  resources :projects




  devise_scope :user do
	  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
	  get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
	  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
	  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  root                    to: 'itineraries#index'
  #get '*path',          to: 'home#index', via: :all
  resources :jobs, :products, :categories, :customers
  resources :dashboards
  
  resources :recommendations do
	  member do
		  get 'approve'
		  get 'reject'
	  end
	  collection do
		  get 'for_approval'
		  get 'approved'
		  get 'rejected'
		  
	  end
  end
  
  
  resources :expenses do
	  member do
		  get 'approve'
		  get 'reject'
	  end
	  collection do
		  get 'search_tcn_no'
		  get 'for_approval'
		  get 'approved'
		  get 'rejected'
		 
	  end
  end
  
  resources :activities do
	  member do
		  get 'approve'
		  get 'reject'
	  end
       collection do
            get 'search_control_no'
		  get 'for_approval'
		  get 'approved'
		  get 'rejected'
		
       end
  end
  resources :itineraries do
	  member do
            get 'completed'
		  get 'update_status_visit_list'
		  get 'approve'
		  get 'reject'
	  end
	  collection do
		  get 'current_week'
		  get 'approved'
		  get 'rejected'
		
	  end
	  
  end
  resources :users do
	  collection do
		  get 'show_current_user'
	  end
  end
  
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
     has_many :tasks, dependent: :destroy
     accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: :all_blank
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:name, tasks_attributes: [:_destroy, :id, :description])
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for @todo_list do |f| %>
     <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
     </div>
     <<h1>Tasks</h1>
     <div data-controller="nested-form">
          <template data-target='nested-form.template'>
               <%= f.fields_for :tasks, Task.new, child_index: 'TEMPLATE_RECORD' do |task| %>
                    <%= render 'task_fields', f: task %>
               <% end %>
          </template>

          <%= f.fields_for :tasks do |task| %>
               <%= render 'task_fields', f: task %>
          <% end %>

          <div data-target="nested-form.add_item">
               <%= link_to "Add Task", "#", data: { action: "nested-form#add_association" } %>
          </div>
     </div>
     <%= f.submit %>
<% end %>

app/views/todo_lists/_task_fields.html.erb
<div class='nested-fields'>
     <div class='form-group'>
          <%= f.hidden_field :_destroy %>
          <%= f.text_field :description, placeholder: 'Description', class: 'form-control' %>
          <small>
               <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %>
          </small>
     </div>
</div>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.name %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo List', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<!--<h1>New Todo List</h1>

<%#= render 'form', todo_list: @todo_list %>

<%#= link_to 'Back', todo_lists_path %>-->
<div class="container-fluid">
     <!-- Page Heading -->
     <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800"></h1>
     </div>

     <!--Start create new itinerary-->
     <div class="row">
          <div class="col-lg-12">
               <div class="card shadow mb-4">
                    <div class="card-header py-3">
                         <h6 class="m-0 font-weight-bold text-primary">Create New Itinerary</h6>
                    </div>
                    <div class="card-body">
                         <div class="card-body">
                              <h1>New Todo List</h1>

                              <%= render 'form', todo_list: @todo_list %>

                              <%= link_to 'Back', todo_lists_path %>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</div>

<!--<h1>New Todo List</h1>

<%#= render 'form', todo_list: @todo_list %>

<%#= link_to 'Back', todo_lists_path %>-->
<div class="container-fluid">
     <!-- Page Heading -->
     <div class="d-sm-flex align-items-center justify-content-between mb-4">
          <h1 class="h3 mb-0 text-gray-800"></h1>
     </div>

     <!--Start create new itinerary-->
     <div class="row">
          <div class="col-lg-12">
               <div class="card shadow mb-4">
                    <div class="card-header py-3">
                         <h6 class="m-0 font-weight-bold text-primary">Create New Itinerary</h6>
                    </div>
                    <div class="card-body">
                         <div class="card-body">
                              <h1>New Todo List</h1>

                              <%= render 'form', todo_list: @todo_list %>

                              <%= link_to 'Back', todo_lists_path %>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo_list.name %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>