config/routes.rb
Rails.application.routes.draw do
  
  resources :todo_lists
  resources :to_lists
  resources :recipes
  resources :projects




  devise_scope :user do
	  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
	  get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end

  devise_for :users, :skip => [:registrations]
  as :user do
	  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
	  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  root                    to: 'itineraries#index'
  #get '*path',          to: 'home#index', via: :all
  resources :jobs, :products, :categories, :customers
  resources :dashboards
  
  resources :recommendations do
	  member do
		  get 'approve'
		  get 'reject'
	  end
	  collection do
		  get 'for_approval'
		  get 'approved'
		  get 'rejected'
		  
	  end
  end
  
  
  resources :expenses do
	  member do
		  get 'approve'
		  get 'reject'
	  end
	  collection do
		  get 'search_tcn_no'
		  get 'for_approval'
		  get 'approved'
		  get 'rejected'
		 
	  end
  end
  
  resources :activities do
	  member do
		  get 'approve'
		  get 'reject'
	  end
       collection do
            get 'search_control_no'
		  get 'for_approval'
		  get 'approved'
		  get 'rejected'
		
       end
  end
  resources :itineraries do
	  member do
            get 'completed'
		  get 'update_status_visit_list'
		  get 'approve'
		  get 'reject'
	  end
	  collection do
		  get 'current_week'
		  get 'approved'
		  get 'rejected'
		
	  end
	  
  end
  resources :users do
	  collection do
		  get 'show_current_user'
	  end
  end
  
end

app/models/job.rb
class Job < ApplicationRecord
     has_many :users, dependent: :destroy
     validates :title, presence: true
     before_save {self.title = title.titlecase}

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
     protect_from_forgery with: Exception
	before_action :check_admin2, only: [:edit, :new]
	
     def index
          @jobs = Job.all.order(:title)
     end

     def show
          @job = Job.find(params[:id])
          @jobs = Job.all.order(:title)
          
     end

     def new
          @job = Job.new
          @jobs = Job.all
     end

     def create
          @job  = Job.new(job_params)
          @jobs = Job.all
          if @job.save
               redirect_to jobs_url
          else
               render 'new'
          end
     end

     def edit
          @job = Job.find(params[:id])
          @jobs = Job.all
     end

     def update
          @job = Job.find(params[:id])
          @jobs = Job.all

          if @job.update_attributes(job_params)
               redirect_to jobs_url
          else
               render 'edit'
          end
     end

     def destroy
          @job = Job.find(params[:id])

          if @job.destroy
               redirect_to jobs_url
          else
               render json: {error: @job.error.messages}, status: 422
          end
     end


     private
          def job_params
               params.require(:job).permit(:title)
          end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<div class="container-fluid">
	
	<!-- Page Heading -->
	<div class="d-sm-flex align-items-center justify-content-between mb-4">
		<h1 class="h3 mb-0 text-gray-800">Positions</h1>
	</div>
	
	
	<div class="row">
		
		<div class="col-lg-6">
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">Edit a Position</h6>
				</div>
				<div class="card-body">
					<div class="row">
						<div class="col-lg-12">
							<div class="p-5">
                                        <%= form_for @job, html: {class: "user"}  do |f|%>
                                             <%= render "shared/error_messages", object: f.object %>
									<div class="form-group">
										<%= f.label :position %>
										<%= f.text_field :title,  class: "form-control form-control-user", placeholder: "Position"  %>
									</div>
									
									<%= f.button :submit , class: "btn btn-primary btn-user btn-block" do %>
										<i class="fas fa-plus"></i> Save Changes
									<% end %>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-lg-6">
			<!-- Basic Card Example -->
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">List of Positions</h6>
				</div>
				<div class="card-body custom-hover"  >
					<% @jobs.each do |job| %>
						<div class="card mb-4 py-3 border-left-primary">
							<%= link_to job do %>
								<div class="card-body">
									<%= job.title + " (" + job.users.count.to_s + ")"%>
								</div>
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	
	</div>

</div>

app/views/jobs/index.html.erb
<div class="container-fluid">

	<!-- Page Heading -->
	<div class="d-sm-flex align-items-center justify-content-between mb-4">
		<h1 class="h3 mb-0 text-gray-800">Positions</h1>
	</div>

     <% if current_user.admin2? %>
	     <div class="row">

		<!-- Earnings (Monthly) Card Example -->
		<div class="col-xl-6 col-md-6 mb-4">
			<div class="card border-left-primary shadow h-100 py-2">
				<div class="card-body">
					<div class="row no-gutters align-items-center">
						<div class="col mr-2">
							<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Number of Jobs</div>
							<div class="h5 mb-0 font-weight-bold text-gray-800">
								<p><%= Job.count %></p>
								<%= link_to new_job_path, class: "btn btn-primary btn-icon-split"  do %>
									<span class="icon text-white-50">
									<i class="fas fa-plus"></i>
									</span>
									<span class="text">Add Position</span>
								<% end %>
							</div>
						</div>
						<div class="col-auto">
							<i class="fas fa-calendar fa-2x text-gray-300"></i>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Earnings (Monthly) Card Example -->
		<div class="col-xl-6 col-md-6 mb-4">
			<div class="card border-left-info shadow h-100 py-2">
				<div class="card-body">
					<div class="row no-gutters align-items-center">
						<div class="col mr-2">
							<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Number of Users</div>
							<div class="h5 mb-0 font-weight-bold text-gray-800">
								<p><%= User.count %><p>
                                        <% if current_user.admin2? %>
								     <%= link_to new_user_url, class:"btn btn-info btn-icon-split" do %>
									<span class="icon text-white-50">
									<i class="fas fa-plus"></i>
									</span>
									<span class="text">Add User</span>
								<% end %>
                                        <% end %>
								</div>
						</div>
						<div class="col-auto">
							<i class="fas fa-user fa-2x text-gray-300"></i>
						</div>
					</div>
				</div>
			</div>
		</div>


	</div>
     <% end %>
	<div class="row">
		<div class="col-lg-6">
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">List of Position</h6>
				</div>
				<div class="card-body custom-hover"  >
					<% @jobs.each do |job| %>
						<div class="card mb-4 py-3 border-left-primary">
							<%= link_to job do %>
								<div class="card-body">
									<%= job.title + " (" + job.users.count.to_s + ")" %>
								</div>
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
		</div>

		<div class="col-lg-6">
			<!-- Basic Card Example -->
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">List of Users</h6>
				</div>
				<div class="card-body custom-hover">
					<% User.all.order(:lastname).each do |user| %>
						<div class="card mb-4 py-3 border-left-info">
							<div class="card-body">
								<%= link_to user do %>
									<%=  user.lastname + ", "  + user.firstname + " " + user.mint + " (#{user.job.title}) " %>
								<% end %>
							</div>


						</div>
					<% end %>
				</div>
			</div>
		</div>

	</div>

</div>

app/views/jobs/new.html.erb
<div class="container-fluid">
	<!-- Page Heading -->
	<div class="d-sm-flex align-items-center justify-content-between mb-4">
		<h1 class="h3 mb-0 text-gray-800">Positions</h1>
	</div>
	<div class="row">
		<div class="col-lg-6">
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">Create a Position</h6>
				</div>
				<div class="card-body">
					<div class="row">
						<div class="col-lg-12">
							<div class="p-5">
								<%= form_for @job, html: {class: "user"}  do |f|%>
									<%= render "shared/error_messages", object: f.object %>
									<div class="form-group">
										<%= f.label :position %>
										<%= f.text_field :title,  class: "form-control form-control-user", placeholder: "Input a position"  %>
									</div>
									
									<%= f.button :submit , class: "btn btn-primary btn-user btn-block" do %>
										<i class="fas fa-plus"></i> Add Position
									<% end %>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-lg-6">
			<!-- Basic Card Example -->
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">List of Positions</h6>
				</div>
				<div class="card-body custom-hover"  >
					<% @jobs.each do |job| %>
						<div class="card mb-4 py-3 border-left-primary">
							<%= link_to job do %>
								<div class="card-body">
									<%= job.title %>
								</div>
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	
	</div>

</div>

app/views/jobs/show.html.erb
<div class="container-fluid">

	<!-- Page Heading -->
	<div class="d-sm-flex align-items-center justify-content-between mb-4">
		<h1 class="h3 mb-0 text-gray-800"></h1>
	</div>

	<div class="row">

		<div class="col-lg-6">
			<!-- Basic Card Example -->
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">Position Details: <%= @job.title + " (" + @job.users.count.to_s + ")"%></h6>
				</div>
				<div class="card-body">
					<div class="row">
						<% @job.users.all.each do |user| %>
							<div class="col-lg-4 custom-hover">
								<%= link_to user do %>
									<div class="card" style="margin-bottom:15px;padding:5px">
										<%= if user.image.blank?
											    cl_image_tag("blank-user-355ba8nijgtrgca9vdzuv4_jqendn.jpg", class: "img-fluid")
										    else
											    image_tag user.image.url, class:"img-fluid"
										    end%>
										<div class="products">
											<%= "#{user.lastname + ", " + user.firstname }".truncate(20) %>
										</div>
									</div>

								<% end %>
							</div>
						<% end %>
					</div>
				</div>
				<% if @job.users.empty? %>
					<div class="card-body">
						<div class="alert alert-warning">
							<h1 class="h3 mb-0 text-gray-800 text-center" >No Records Found</h1>
						</div>
					</div>
				<% else %>
                         <% if current_user.admin2? %>
					     <div class="card-body">
						<div class="row">
							<div class="col-lg-6">
								<%= link_to edit_job_url, class: "btn btn-info btn-icon-split btn-block btn-lg"  do %>
										<span class="icon text-white-50">
										<i class="fas fa-edit"></i>
										</span>
									<span class="text">Modify</span>
								<% end %>
							</div>
                                        <div class="col-lg-6">
                                             <%= link_to job_url, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-danger btn-icon-split btn-block btn-lg"  do %>
										<span class="icon text-white-50">
										<i class="fas fa-trash"></i>
										</span>
                                                  <span class="text">Delete</span>
                                             <% end %>
                                        </div>
						</div>
					</div>
                         <% end %>
				<% end %>
			</div>
		</div>
		<div class="col-lg-6">
			<!-- Basic Card Example -->
			<div class="card shadow mb-4">
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">List of Positions</h6>
				</div>
				<div class="card-body custom-hover"  >
					<% @jobs.each do |job| %>
						<div class="card mb-4 py-3 border-left-primary">
							<%= link_to job do %>
								<div class="card-body">
									<%= job.title + " (" + job.users.count.to_s + ")" %>
								</div>
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
		</div>

	</div>
</div>